version: "3"

services:
    {{cookiecutter.project_slug}}:
        image: {{cookiecutter.project_slug}}
        build: app
        container_name: {{cookiecutter.project_slug}}
        ports:
            - "${PROD_PORT:-80}:80"
        environment:
            - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - DB_HOST=${DB_HOST:-{{cookiecutter.project_slug}}_db}
            - SENTRY_DSN
        depends_on:
            - {{cookiecutter.project_slug}}_db

    {{cookiecutter.project_slug}}_db:
        image: {{cookiecutter.project_slug}}_db
        build: db
        container_name: {{cookiecutter.project_slug}}_db
        volumes:
            - ${DOCKER_VOLUMES:-~/docker_volumes/{{cookiecutter.project_slug}}}/db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD
