version: "3"

services:
    {{cookiecutter.project_slug}}:
        image: {{cookiecutter.project_slug}}
        build: app
        container_name: {{cookiecutter.project_slug}}
        ports:
            - "${PROD_PORT:-80}:80"
        environment:
            - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - DB_HOST=${DB_HOST:-{{cookiecutter.project_slug}}_db}
            - SENTRY_DSN
            {%- if cookiecutter.add_celery == "yes" %}
            - BROKER_HOST=${BROKER_HOST:-{{cookiecutter.project_slug}}_broker}
            {%- endif %}
        depends_on:
            - {{cookiecutter.project_slug}}_db
            {%- if cookiecutter.add_celery == "yes" %}
            - {{cookiecutter.project_slug}}_broker
            - {{cookiecutter.project_slug}}_workers
            {%- endif %}
        restart: always

    {%- if cookiecutter.add_celery == "yes" %}

    {{cookiecutter.project_slug}}_workers:
        image: {{cookiecutter.project_slug}}
        build: app
        container_name: {{cookiecutter.project_slug}}_workers
        command: workers
        environment:
            - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - DB_HOST=${DB_HOST:-{{cookiecutter.project_slug}}_db}
            - SENTRY_DSN
            - BROKER_HOST=${BROKER_HOST:-{{cookiecutter.project_slug}}_broker}
        depends_on:
            - {{cookiecutter.project_slug}}_db
            - {{cookiecutter.project_slug}}_broker
        restart: always
    {%- endif %}

    {{cookiecutter.project_slug}}_db:
        image: {{cookiecutter.project_slug}}_db
        build: db
        container_name: {{cookiecutter.project_slug}}_db
        volumes:
            - ${DOCKER_VOLUMES:-~/docker_volumes/{{cookiecutter.project_slug}}}/db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD
        restart: always

    {%- if cookiecutter.add_celery == "yes" %}

    {{cookiecutter.project_slug}}_broker:
        image: {{cookiecutter.project_slug}}_broker
        build: broker
        container_name: {{cookiecutter.project_slug}}_broker
        volumes:
            - ${DOCKER_VOLUMES:-~/docker_volumes/{{cookiecutter.project_slug}}}/broker/lib:/var/lib/rabbitmq
        restart: always
    {%- endif %}
